version: '3.7'

services:
  recipes:
    image: bernieke/recipes
    logging:
      options:
        max-size: 2m
    environment:
      - GUNICORN=1
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=recipes
      - SQL_USER=recipes
      - SQL_PASSWORD=recipes
      - SQL_HOST=postgres
      - SQL_PORT=5432
    volumes:
      - static:/var/www/recipes
    depends_on:
      - postgres
  postgres:
    image: postgres
    logging:
      options:
        max-size: 2m
    volumes:
      - database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=recipes
      - POSTGRES_USER=recipes
      - POSTGRES_PASSWORD=recipes
  nginx:
    image: nginx
    logging:
      options:
        max-size: 2m
    volumes:
      - static:/var/www/recipes:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:80
    depends_on:
      - recipes

volumes:
  database:
  static:
