# Generated by Django 2.2.1 on 2019-06-06 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_floz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={
                'ordering': ['name'],
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='measured',
        ),
    ]
