# Generated by Django 2.2.1 on 2019-06-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_measured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={
                'ordering': ('order', 'name'),
                'verbose_name': 'unit',
                'verbose_name_plural': 'units'
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='order',
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name='order'),
        ),
    ]
