# Generated by Django 2.2.1 on 2019-06-06 13:05

from django.db import migrations
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_add_order_to_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=django_markdown.models.MarkdownField(
                blank=True, verbose_name='recipe'),
        ),
    ]
