# Generated by Django 2.2.1 on 2019-08-02 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_migrate_ingredients_and_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientinrecipe',
            name='ingredient',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(
                blank=True, max_length=254, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ingredientinrecipe',
            name='ingredient_unit',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='recipes.IngredientUnit', verbose_name='ingredient'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
    ]
