# Generated by Django 2.2.15 on 2020-09-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_remove_old_ingredient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alias',
            name='order',
            field=models.PositiveSmallIntegerField(
                db_index=True, default=0, verbose_name='order'),
        ),
    ]
