# Generated by Django 2.2.15 on 2020-09-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alias_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monday_lunch_dishes', models.TextField(blank=True)),
                ('monday_dinner_dishes', models.TextField(blank=True)),
                ('tuesday_lunch_dishes', models.TextField(blank=True)),
                ('tuesday_dinner_dishes', models.TextField(blank=True)),
                ('wednesday_lunch_dishes', models.TextField(blank=True)),
                ('wednesday_dinner_dishes', models.TextField(blank=True)),
                ('thursday_lunch_dishes', models.TextField(blank=True)),
                ('thursday_dinner_dishes', models.TextField(blank=True)),
                ('friday_lunch_dishes', models.TextField(blank=True)),
                ('friday_dinner_dishes', models.TextField(blank=True)),
                ('saturday_lunch_dishes', models.TextField(blank=True)),
                ('saturday_dinner_dishes', models.TextField(blank=True)),
                ('sunday_lunch_dishes', models.TextField(blank=True)),
                ('sunday_dinner_dishes', models.TextField(blank=True)),
                ('monday_lunch_note', models.TextField(blank=True)),
                ('monday_dinner_note', models.TextField(blank=True)),
                ('tuesday_lunch_note', models.TextField(blank=True)),
                ('tuesday_dinner_note', models.TextField(blank=True)),
                ('wednesday_lunch_note', models.TextField(blank=True)),
                ('wednesday_dinner_note', models.TextField(blank=True)),
                ('thursday_lunch_note', models.TextField(blank=True)),
                ('thursday_dinner_note', models.TextField(blank=True)),
                ('friday_lunch_note', models.TextField(blank=True)),
                ('friday_dinner_note', models.TextField(blank=True)),
                ('saturday_lunch_note', models.TextField(blank=True)),
                ('saturday_dinner_note', models.TextField(blank=True)),
                ('sunday_lunch_note', models.TextField(blank=True)),
                ('sunday_dinner_note', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ('order',), 'verbose_name': 'alias', 'verbose_name_plural': 'aliases'},
        ),
    ]
