# Generated by Django 2.2.15 on 2020-10-06 10:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_add_week_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='last_change_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='menu',
            name='last_change_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
