# Generated by Django 2.2.19 on 2021-02-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_add_last_change_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='popularity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('-popularity', 'title'), 'verbose_name': 'recipe', 'verbose_name_plural': 'recipes'},
        ),
    ]
