# Generated by Django 2.2.24 on 2021-06-05 11:50

from datetime import date

import django.core.validators
from django.db import migrations, models


today = date.today()
year, week = today.year, int(today.strftime('%V'))


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_copy_weekmenu_notes_to_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alias',
            options={'ordering': ['order'], 'verbose_name': 'alias',
                     'verbose_name_plural': 'aliases'},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ingredient',
                     'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='ingredientinrecipe',
            options={'ordering': ['order'], 'verbose_name': 'ingredient',
                     'verbose_name_plural': 'ingredients'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['year', 'week']},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-popularity', 'title'],
                     'verbose_name': 'recipe',
                     'verbose_name_plural': 'recipes'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order', 'name'], 'verbose_name': 'tag',
                     'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['order', 'name'], 'verbose_name': 'unit',
                     'verbose_name_plural': 'units'},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'ordering': ['from_unit', 'to_unit'],
                     'verbose_name': 'unit conversion',
                     'verbose_name_plural': 'unit conversions'},
        ),
        migrations.AddField(
            model_name='menu',
            name='week',
            field=models.PositiveSmallIntegerField(
                default=week,
                validators=[django.core.validators.MaxValueValidator(53)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='year',
            field=models.PositiveIntegerField(default=year),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('year', 'week')},
        ),
    ]
