# Generated by Django 3.2.5 on 2021-07-06 07:51

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_menu_dishes_with_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe',
            field=martor.models.MartorField(blank=True, verbose_name='recipe'),
        ),
    ]
