# Generated by Django 3.2.5 on 2021-07-07 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0023_alter_recipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientunit',
            name='use_in_recipe',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
