# Generated by Django 3.2.5 on 2021-07-07 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_alter_ingredientunit_use_in_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='primary_unit',
            new_name='shopping_unit',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='shopping_unit',
            field=models.ForeignKey(
                blank=True, default=None, null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='shopping_unit', to='recipes.unit',
                verbose_name='shopping unit'),
        ),
        migrations.AlterField(
            model_name='ingredientunit',
            name='use_in_recipe',
            field=models.BooleanField(
                default=False, verbose_name='use in recipe'),
        ),
    ]
