# Generated by Django 3.2.10 on 2022-01-03 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0027_menu_dishes_with_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientunit',
            name='use_in_recipe',
            field=models.BooleanField(
                default=True, verbose_name='use in recipe'),
        ),
    ]
